### ISSUE TITLE
UltraStar Creator AppImage contains linuxdeployqt

### ISSUE THREAD

**Issue by probonopd** [UltraStar-Deluxe/UltraStar-Creator#2]
Something is clearly going wrong here:

```
UltraStar-Creator-ad87c37-x86_64.AppImage 
Usage: linuxdeployqt (...)
```

Please see the README.md of linuxdeployqt for examples on how to use it in conjunction with Travis CI. Let me know if you need further assistance.

**Comment by bohning** [comment]
Thanks for your message, I really appreciate your offer to help. I studied the README.md and gave it a shot, but obviously it fails here:

`fuse: failed to open /dev/fuse: Operation not permitted`

I pretty much followed the steps outlined [here](https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci) and was able to create an AppImage on my local machine this way.
I assume it fails on Travis because it cannot mount the linuxdeployqt.AppImage without sudo? Or do I have to install fuse via apt-get before?

Thanks in advance for your help.

**Comment by probonopd** [comment]
Yes, I'm a bit puzzled why you are getting this message on Travis CI. `.travis.yml` files starting with

```
language: cpp
compiler: gcc
sudo: require
dist: trusty
```

do not seem to have this issue.

https://github.com/search?l=YAML&q=linuxdeployqt&type=Code&utf8=%E2%9C%93

**Comment by bohning** [comment]
Yes, I am building in a container, so I don't have sudo available (ATM/AFAIK)...

**Comment by DeinAlptraum** [comment]
This doesn't seem to be the case anymore. Travis CI is also not used anymore.
